pipeline {
    environment {
        DOCKERHUB_CREDENTIALS= credentials('docker-hub-credentials')
    }
    agent any
    tools {
        maven 'maven'
        jdk 'jdk17'
    }
    stages {
        stage ('Initialize') {
            steps {
                sh '''
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"
                '''
            }
        }
        stage ('Build') {
            steps {
                sh '''
                    cd my-app
                    mvn -B -DskipTests clean package
                '''
            }
        }
        stage('Test') {
            steps {
                sh '''
                    cd my-app
                    mvn test
                '''
            }
        }
        stage('docker version') {
            steps {
                sh "docker version" // DOCKER_CERT_PATH is automatically picked up by the Docker client
            }
        }
        stage('Login to Docker Hub') {
            steps{
                sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
                echo 'Login Completed'
            }
        }
        stage('docker build') {
            steps {
                sh '''
                    cd my-app
                    docker build -t witchpoutraining/my-app .
                '''
            }
        }
        stage('docker push') {
            steps {
                sh '''
                    cd my-app
                    docker push witchpoutraining/my-app
                '''
            }
        }
        stage('docker logout') {
            steps {
                sh "docker logout" // DOCKER_CERT_PATH is automatically picked up by the Docker client
            }
        }
    }
}