pipeline {
    environment {
        registry = "hub.docker.com/docker-test"
        registryCredential = 'docker-hub-credentials'
        dockerImage = ''
      }
    agent any
    tools {
        maven 'maven'
        jdk 'jdk17'
    }
    stages {
        stage ('Initialize') {
            steps {
                sh '''
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"
                '''
            }
        }

        stage ('Build') {
            steps {
                sh '''
                    cd my-app
                    mvn -B -DskipTests clean package
                '''
            }
        }
        stage('Test') {
            steps {
                sh '''
                    cd my-app
                    mvn test
                '''
            }
            post {
                always {
                    junit  skipPublishingChecks: true, testResults: 'my-app/target/surefire-reports/*.xml'
                }
            }
        }
        stage('Docker Build') {
                    steps {
                        sh '''
                            cd my-app
                            docker build -t my-app .
                        '''
                    }
                }
        stage('Building image') {
              steps{
                script {
                    cd my-app
                    dockerImage = docker.build registry + ":$BUILD_NUMBER"
                }
              }
            }
            stage('Deploy Image') {
              steps{
                 script {
                    cd my-app
                    docker.withRegistry( '', registryCredential ) {
                    dockerImage.push()
                  }
                }
              }
            }
            stage('Remove Unused docker image') {
              steps{
                cd my-app
                sh "docker rmi $registry:$BUILD_NUMBER"
              }
            }
    }
}