pipeline {
    agent any
    environment {
        KUBECONFIG='/var/lib/jenkins/.kube/k3s.yaml'
    }
    tools { 
        maven 'maven' 
        jdk 'jdk17' 
    }
    stages {
        stage ('Initialize') {
            steps {
                sh '''
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"
                ''' 
            }
        }

        stage ('Build') {
            steps {
                sh '''
                    cd testexample
                    mvn -B -DskipTests clean package
                ''' 
            }
        }
        stage('Test') {
            steps {
                sh '''
                    cd testexample
                    mvn test
                ''' 
            }
            post {
                always {
                    junit  skipPublishingChecks: true, testResults: 'testexample/target/surefire-reports/*.xml'
                }
            }
        }
        stage('kubectl get all') {
                    steps {
                        sh '''
                            echo $USER
                            echo $KUBECONFIG
                            cd testexample
                            kubectl get all --all-namespaces
                            kubectl apply -f demo-config.yaml
                            kubectl apply -f demo.yaml
                        '''
                    }
                }
    }
}