pipeline {
    agent any
    environment {
        KUBECONFIG='/var/lib/jenkins/.kube/k3s.yaml'
    }
    stages {
        stage('kubectl get all') {
            steps {
                sh '''
                    cd deployment-helm-ridha/demo-ridha
                    helm install demo-ridha .
                '''
            }
        }
    }
}