pipeline {
    environment {
        registry = "gustavoapolinario/docker-test"
        registryCredential = 'dockerhub'
        app = ''
    }
    stages {
        stage('Build') {
            steps {
                script {
                    app = docker.build("starwit-app")
                }
            }
        }
    }
}