pipeline {
    environment {
        registry = "gustavoapolinario/docker-test"
        registryCredential = 'dockerhub'
        app = ''
    }
    stages {
        stage('Build') {
            steps {
                script {
                    app = docker.build("starwit-app")
                }
            }
        }
        stage('Test image') {
            /* Ideally, we would run a test framework against our image.
            * For this example, we're using a Volkswagen-type approach ;-) */

            app.inside {
                sh 'echo "Tests passed"'
            }
        }
    }
}