pipeline {
    agent any
    environment {     
        KUBECONFIG='/var/lib/jenkins/.kube/k3s.yaml'     
    } 
    stages {
        stage('kubectl get all') {
            steps {
                sh '''
                    cd deploymentCM/demo
                    helm install demoCM .
                ''' 
            }
        }
    }
}