apiVersion: v1
data:
  index.html: |-
    <html>

    <head>
        <title>Hello Training!</title>
    </head>

    <body>Hello Training!</body>

    </html>
kind: ConfigMap
metadata:
  name: hello-world
