pipeline {
    agent any
    stages {
        stage('kubectl get all') {
            steps {
                sh '''
                    echo $USER
                    echo $KUBECONFIG
                    cd deployment
                    kubectl get all --all-namespaces
                    kubectl -n default apply -f test-config.yaml
                ''' 
            }
        }
    }
}