pipeline {
    agent any
    stages {
        stage('Deployment') {
            steps {
                script {
                    kubernetesDeploy(configs: "deployment/test-config.yaml")
                }
            }
        }
}