pipeline {
    agent any
    environment {     
        KUBECONFIG='/var/lib/jenkins/.kube/k3s.yaml'     
    } 
    stages {
        stage('kubectl get all') {
            steps {
                sh '''
                    echo $USER
                    echo $KUBECONFIG
                    cd deployment
                    kubectl get all --all-namespaces
                    kubectl -n default apply -f test-config.yaml
                    kubectl create configmap hello-world --from-file index.html
                    kubectl apply -f demo.yml
                ''' 
            }
        }
    }
}