pipeline {
  agent any
    environment {
    // stored into https://jenkins.starwit-infra.de:1443/manage/credentials/
        DOCKERHUB_CREDENTIALS= credentials('docker-hub-credentials')
    }
    stages {
        stage('docker version') {
            steps {
                sh "docker version" // DOCKER_CERT_PATH is automatically picked up by the Docker client
            }
        }
        stage('Login to Docker Hub') {
            steps{
                sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
                echo 'Login Completed'
            }
        }
        stage('docker build') {
            steps {
                sh '''
                    cd my-app-ridha
                    docker build -t witchpoutraining/my-app-ridha .
                '''
            }
        }
        stage('docker push') {
            steps {
                sh '''
                    cd my-app-ridha
                    docker push witchpoutraining/my-app-ridha
                '''
            }
        }
        stage('docker logout') {
            steps {
                sh "docker logout" // DOCKER_CERT_PATH is automatically picked up by the Docker client
            }
        }
    }
}