pipeline {
    agent any
    tools {
        maven 'maven'
        jdk 'jdk17'
    }
    stages {
        stage ('Initialize') {
            steps {
                sh '''
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"
                '''
            }
        }

        stage ('Build') {
            steps {
                sh '''
                    cd my-app-ridha
                    mvn -B -DskipTests clean package
                '''
            }
        }
        stage('Test') {
            steps {
                sh '''
                    cd my-app-ridha
                    mvn test
                '''
            }
            post {
                always {
                    junit  skipPublishingChecks: true, testResults: 'my-app-ridha/target/surefire-reports/*.xml'
                }
            }
        }
        stage('Docker Build') {
            steps {
                sh '''
                    cd my-app-ridha
                    docker build -t my-app-ridha .
                '''
            }
        }
    }
}