pipeline {
    agent any
    tools { 
        maven 'maven' 
        jdk 'jdk17' 
    }
    environment {     
        DOCKERHUB_CREDENTIALS= credentials('docker-hub-credentials')     
    }
    stages {
        stage ('Build') {
            steps {
                sh '''
                    cd starwit-app
                    mvn -B -DskipTests clean package
                ''' 
            }
        }
        stage('Test') {
            steps {
                sh '''
                    cd starwit-app
                    mvn test
                ''' 
            }
            post {
                always {
                    junit  skipPublishingChecks: true, testResults: 'starwit-app/target/surefire-reports/*.xml'
                }
            }
        }
        stage('Login to Docker Hub') {      	
            steps{                       	
                sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'                		
                echo 'Login Completed'      
            }           
        } 
        stage('docker build') {
            steps {
                sh '''
                    cd starwit-app
                    docker build -t witchpoutraining/starwit-app .
                ''' 
            }
        }
        stage('docker push') {
            steps {
                sh '''
                    cd starwit-app
                    docker push witchpoutraining/starwit-app
                ''' 
            }
        }
            post {
                always {
                    steps {
                        sh '''
                            docker logout
                        ''' 
                    }
                }
            }
    }
}